/** River Margin design system: source-aware content is held as bilingual field notes, preserving legal terms and explicit public-data limits. */
export const externalLinks = {
  ulm: "https://ulm.ac.id/id/", ulmHistory: "https://ulm.ac.id/id/history/", ulmLeadership: "https://ulm.ac.id/id/10148-2/", faculty: "https://fh.ulm.ac.id/", facultyHistory: "https://fh.ulm.ac.id/sejarah-fakultas/", facultyLeadership: "https://fh.ulm.ac.id/profil/organisasi-fakultas/pimpinan/", facultyStaff: "https://fh.ulm.ac.id/profil/organisasi-fakultas/tenaga-pendidik-dosen/", pidana: "https://fh.ulm.ac.id/bagian-hukum/pidana/", curriculum: "https://fh.ulm.ac.id/formasi-mata-kuliah-kurikulum/", curriculumPdf: "https://fh.ulm.ac.id/wp-content/uploads/2023/04/SKS.pdf", facilities: "https://fh.ulm.ac.id/sarana-prasarana/", mootCourtPhoto: "https://fh.ulm.ac.id/img_8181edt/", hukumonlineCorner: "https://ulm.ac.id/id/2024/08/01/ulm-miliki-hukumonline-corner-pertama-di-kalimantan-permudah-akses-literasi-dan-referensi-hukum-terpercaya/", library: "https://lib.ulm.ac.id/id/", alumni: "https://fh.ulm.ac.id/pusat-layanan-alumni/", accreditation: "https://fh.ulm.ac.id/profil/akreditasi-dan-sertifikasi/", accreditationNews: "https://fh.ulm.ac.id/2026/06/05/prodi-s1-hukum-fh-ulm-raih-akreditasi-baik-sekali-dari-ban-pt/", instagram: "https://www.instagram.com/fh.ulm/", kejaksaan: "https://rekrutmen.kejaksaan.go.id/", kejaksaanNews: "https://rekrutmen.kejaksaan.go.id/pengumuman", pppj: "https://badiklat.kejaksaan.go.id/berita/s/jaksa-agung-lantik-503-jaksa-baru-burhanuddin-saya-butuh-jaksa-4c2d6", repository: "https://github.com/kecrwn/Saku-Hukum-ULM",
};
export const imagery = { hero: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/RjSomHsVJHEZdUfP.jpg", materials: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/MvEAZzYSBSpKaLrk.jpg", riverCampus: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/HVpVWvKUBUSKNJyu.jpg", mootIllustration: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/XTDGHGSfuojFYNIC.jpg", mark: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/GhBkxJffkVyUAzOJ.png", officialMoot: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/pPVdywiJBmerfPCP.webp" };
export const criminalRequiredCourses = [
  { code: "BPHPI3701", id: "Sistem Peradilan Pidana", en: "Criminal Justice System" }, { code: "BPHPI3707", id: "Tindak Pidana di Bidang Sumber Daya Alam", en: "Crimes in the Natural Resources Sector" }, { code: "BPHPI3703", id: "Viktimologi", en: "Victimology" }, { code: "BPHPI3704", id: "Perbandingan Hukum Pidana", en: "Comparative Criminal Law" }, { code: "BPHPI3705", id: "Tindak Pidana di Bidang Ekonomi", en: "Crimes in the Economic Sector" }, { code: "BPHPI3706", id: "Hukum Penitensier", en: "Penitentiary Law" },
];
export const criminalElectiveCourses = [
  { code: "BPHPI3702", id: "Kriminologi", en: "Criminology" }, { code: "BPHPI3708", id: "Tindak Pidana Telematika", en: "Telematics Crime" }, { code: "BPHPI3709", id: "Hukum Pidana Internasional", en: "International Criminal Law" }, { code: "BPHPI3710", id: "Aspek Pidana dalam Media Massa", en: "Criminal-Law Aspects of Mass Media" }, { code: "BPHPI3711", id: "Hukum Pidana Adat", en: "Customary Criminal Law" }, { code: "BPHPI3712", id: "Psikologi Kriminal", en: "Criminal Psychology" }, { code: "BPHPI3713", id: "Hukum Pidana Anak", en: "Juvenile Criminal Law" }, { code: "BPHPI3714", id: "Hukum Pidana Islam", en: "Islamic Criminal Law" }, { code: "BPHPI3715", id: "Tindak Pidana Pemilu", en: "Election Crime" }, { code: "BPHPI3716", id: "Tindak Pidana Kekayaan Intelektual", en: "Intellectual Property Crime" },
];
export const semesterFocus = [
  { semester: "I", credits: "19 SKS", id: "Fondasi studi hukum", en: "Foundations of legal study" }, { semester: "II", credits: "21 SKS", id: "Termasuk Hukum Pidana (3 SKS)", en: "Includes Criminal Law (3 credits)" }, { semester: "III", credits: "23 SKS", id: "Hukum Pidana Lanjut & Hukum Acara Pidana", en: "Advanced Criminal Law & Criminal Procedure" }, { semester: "IV", credits: "23 SKS", id: "Tindak Pidana Tertentu dalam KUHP", en: "Specific Crimes in the Criminal Code" }, { semester: "V", credits: "23 SKS", id: "Termasuk Tindak Pidana Korupsi", en: "Includes Corruption Crime" }, { semester: "VI", credits: "Dokumen menunjukkan praktik", id: "Praktik Peradilan Pidana (2 SKS) dan peminatan", en: "Criminal Court Practice (2 credits) and specialization" },
];
export const translations = {
  id: { nav: [["Beranda", "/"], ["Tentang ULM", "/tentang"], ["Kurikulum", "/kurikulum"], ["Fasilitas", "/fasilitas"], ["Dosen & Staf", "/dosen"], ["Kemahasiswaan", "/kemahasiswaan"], ["Apa Kata Mereka", "/perspektif"], ["Jalur Karier", "/karier"], ["Tautan", "/tautan"]], viewSource: "Buka sumber resmi", source: "Sumber", overview: "Ikhtisar", backHome: "Kembali ke beranda", updated: "Diverifikasi 27 Agustus 2026", dataLimit: "Tidak tersedia secara publik", official: "resmi", personalNotice: "Situs pribadi untuk keperluan studi. Tidak berafiliasi secara resmi dengan Universitas Lambung Mangkurat.", footerNote: "Catatan akademik yang ditautkan kembali ke sumber primer.", openMenu: "Buka menu navigasi", closeMenu: "Tutup menu navigasi", switchLanguage: "Beralih ke bahasa Inggris" },
  en: { nav: [["Home", "/"], ["About ULM", "/tentang"], ["Curriculum", "/kurikulum"], ["Facilities", "/fasilitas"], ["Faculty & Staff", "/dosen"], ["Student Life", "/kemahasiswaan"], ["What They’re Saying", "/perspektif"], ["Career Path", "/karier"], ["Links", "/tautan"]], viewSource: "Open official source", source: "Source", overview: "Overview", backHome: "Back to home", updated: "Verified 27 August 2026", dataLimit: "Not publicly available", official: "official", personalNotice: "A personal site for study purposes. It is not officially affiliated with Universitas Lambung Mangkurat.", footerNote: "Academic notes linked back to primary sources.", openMenu: "Open navigation menu", closeMenu: "Close navigation menu", switchLanguage: "Switch to Bahasa Indonesia" },
} as const;
