/** River Margin design system: public perspectives appear as source-marked reading cards—paraphrased, scoped, and never treated as a ratings feed. */
import "./perspectives.css";
import { ArrowUpRight, Eye, FileText, MessageCircleMore, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { useLanguage } from "@/contexts/LanguageContext";

type Perspective = { id: string; platform: "Quora" | "Hukumonline"; scopeId: string; scopeEn: string; relationshipId: string; relationshipEn: string; dateId: string; dateEn: string; titleId: string; titleEn: string; bodyId: string; bodyEn: string; href: string };

const perspectives: Perspective[] = [
  { id: "P-01", platform: "Quora", scopeId: "ULM secara umum", scopeEn: "ULM generally", relationshipId: "Alumni Fakultas Teknik", relationshipEn: "Faculty of Engineering alumnus", dateId: "Diperbarui 6 tahun lalu", dateEn: "Updated 6 years ago", titleId: "Jembatan dua kampus", titleEn: "A bridge between two campuses", bodyId: "Seorang alumnus Teknik Sipil ULM mengenang perjalanan akademiknya yang kerap berpindah antara Banjarmasin dan Banjarbaru. Baginya, perjalanan itu memperluas pertemanan lintas prodi dan terasa didukung oleh suasana dosen yang tidak mengintimidasi.", bodyEn: "A ULM Civil Engineering alumnus recalls academic work that often moved between Banjarmasin and Banjarbaru. For her, those trips widened friendships across programmes and came with a teaching atmosphere that did not feel intimidating.", href: "https://id.quora.com/Apa-hal-yang-paling-kamu-sukai-dari-berkuliah-di-Universitas-Lambung-Mangkurat/answer/Farikha-Ratna-Sekar" },
  { id: "P-02", platform: "Quora", scopeId: "ULM secara umum", scopeEn: "ULM generally", relationshipId: "Alumni Ilmu Pemerintahan", relationshipEn: "Government Science alumnus", dateId: "Diposting 5 tahun lalu", dateEn: "Posted 5 years ago", titleId: "Keragaman sebagai pelajaran", titleEn: "Diversity as a lesson", bodyId: "Seorang lulusan Ilmu Pemerintahan menggambarkan pertemanan ULM sebagai perjumpaan dengan beragam daerah dan latar budaya. Ia memandang pengalaman tersebut memperluas cara pandang, dan mengatakan hubungan antarteman tetap terjaga setelah lulus.", bodyEn: "A Government Science graduate describes ULM friendships as an encounter with peers from varied regions and cultural backgrounds. He sees that experience as broadening his outlook, with peer ties continuing after graduation.", href: "https://id.quora.com/Apa-hal-yang-paling-kamu-sukai-dari-berkuliah-di-Universitas-Lambung-Mangkurat/answer/Erwin-Erlangga" },
  { id: "P-03", platform: "Quora", scopeId: "ULM secara umum", scopeEn: "ULM generally", relationshipId: "Mahasiswa Pendidikan Kimia/Kimia", relationshipEn: "Chemistry Education/Chemistry student", dateId: "Diperbarui 6 tahun lalu", dateEn: "Updated 6 years ago", titleId: "Bahasa lokal di ruang kelas", titleEn: "Local language in the classroom", bodyId: "Seorang mahasiswa Pendidikan Kimia/Kimia mengamati bahwa sebagian pengajar kadang memadukan bahasa Banjar dan bahasa Indonesia. Menurut pengamatannya, konteks lokal tersebut menarik dan dapat membantu pemahaman bagi banyak mahasiswa yang akrab dengan bahasa Banjar.", bodyEn: "A Chemistry Education/Chemistry student observes that some instructors sometimes combine Banjar and Indonesian. In her view, this local context is engaging and can support comprehension for many students familiar with Banjar.", href: "https://id.quora.com/Apa-hal-yang-paling-kamu-sukai-dari-berkuliah-di-Universitas-Lambung-Mangkurat/answer/Rahmia-Amien" },
  { id: "H-01", platform: "Hukumonline", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Lulusan FH ULM dalam wawancara", relationshipEn: "FH ULM graduate interviewed", dateId: "31 Desember 2024", dateEn: "31 December 2024", titleId: "Menghargai proses belajar", titleEn: "Valuing the learning process", bodyId: "Dalam wawancara setelah dinobatkan sebagai wisudawati terbaik, seorang lulusan FH ULM menceritakan kecemasan di awal kuliah dan upayanya menyeimbangkan kegiatan. Ia menempatkan proses di samping capaian nilai, serta menyebut dukungan dosen sebagai bagian bermakna dari perjalanan akademiknya.", bodyEn: "In an interview after being named the top graduate, an FH ULM alumna describes early anxiety and the effort to balance campus activities. She places the process alongside grades, and sees lecturer support as meaningful in her academic journey.", href: "https://www.hukumonline.com/berita/a/lulusan-terbaik-fh-universitas-lambung-mangkurat--alya-amani-mengejar-profesi-dosen-hukum-tata-negara-lt67736b9dd66bb/" },
  { id: "H-02", platform: "Hukumonline", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Pilihan mahasiswa yang dilaporkan dalam survei", relationshipEn: "Student selection reported in a survey", dateId: "8 Januari 2025", dateEn: "8 January 2025", titleId: "Mengapresiasi kelas yang interaktif", titleEn: "Appreciating an interactive class", bodyId: "Hukumonline melaporkan bahwa Prof. Mirza Satria Buana dipilih sebagai salah satu dosen yang dihormati dan disukai mahasiswa FH ULM dalam survei Dosen Hukum Favorit 2024. Artikel itu mengaitkan apresiasi tersebut dengan gaya pengajaran yang interaktif dan bersemangat; ini adalah ringkasan laporan survei, bukan klaim tentang seluruh mahasiswa FH ULM.", bodyEn: "Hukumonline reports that Prof. Mirza Satria Buana was selected as one of the lecturers respected and liked by FH ULM students in its 2024 Favourite Law Lecturer survey. The article connects that appreciation to interactive, energetic teaching; this is a summary of a reported survey, not a claim about every FH ULM student.", href: "https://www.hukumonline.com/berita/a/dedikasi-tanpa-batas--2-dosen-hukum-favorit-pilihan-fh-ulm-dan-fh-uph-lt677e0dc4d9ae2/?page=2" },
  { id: "H-03", platform: "Hukumonline", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Perspektif pimpinan fakultas saat itu", relationshipEn: "Then-faculty-leadership perspective", dateId: "16 September 2024", dateEn: "16 September 2024", titleId: "Belajar hukum yang berakar pada tempat", titleEn: "Legal study rooted in place", bodyId: "Dalam wawancara 2024, Dr. Achmad Faishal—yang saat itu menjabat Dekan FH ULM—menjelaskan orientasi pendidikan hukum yang terhubung dengan kearifan lokal dan sumber daya lahan basah. Ia juga menautkan pengembangan kurikulum dengan kebutuhan memahami persoalan hukum yang muncul bersama perubahan teknologi.", bodyEn: "In a 2024 interview, Dr. Achmad Faishal—then Dean of FH ULM—describes a legal-education orientation connected to local wisdom and wetland resources. He also links curriculum development to understanding legal issues emerging through technological change.", href: "https://www.hukumonline.com/berita/a/melihat-keunggulan-fh-universitas-lambung-mangkurat-lt66e7c1d4321c7/" },
];

const platformInfo = { Quora: { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/FFJJTIbcqWLGrcWy.svg", color: "#B92B27", actionId: "Baca jawaban lengkap di Quora", actionEn: "Read the full answer on Quora" }, Hukumonline: { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/aXRCPoXJFLPJoLmA.png", color: "#03447d", actionId: "Baca liputan lengkap di Hukumonline", actionEn: "Read the full post on Hukumonline" } };

function RiverThread({ label }: { label: string }) { return <div className="perspective-river-thread" aria-hidden="true"><svg viewBox="0 0 500 25" preserveAspectRatio="none"><path d="M1 14 C52 2, 96 24, 150 13 S252 2, 307 14 S405 24, 499 8" /></svg><span>{label}</span></div>; }

export default function Perspectives() {
  const { isIndonesian } = useLanguage();
  return <>
    <PageIntro label={isIndonesian ? "Apa Kata Mereka" : "What They’re Saying"} title={isIndonesian ? "Perspektif publik, dibaca dengan konteks." : "Public perspectives, read in context."} summary={isIndonesian ? "Enam catatan yang dapat dibuka publik ini dipilih karena memiliki sumber asli yang jelas. Semuanya diparafrasekan; tidak ada teks ulasan atau komentar penuh yang disalin." : "These six publicly accessible notes were selected because their original sources are clear. Every entry is paraphrased; no full review or comment is republished."} sourceCount={isIndonesian ? "6 perspektif • 2 platform publik" : "6 perspectives • 2 public platforms"} />
    <section className="content-width perspective-method"><div className="method-heading"><p className="eyebrow">{isIndonesian ? "Cara membaca" : "How to read this"}</p><h2>{isIndonesian ? "Bukan peringkat. Bukan kesimpulan umum." : "Not a rating. Not a general conclusion."}</h2></div><div className="method-points"><div><Eye size={18} /><p>{isIndonesian ? "Setiap kartu menjelaskan apakah ia berbicara tentang FH ULM atau ULM secara umum." : "Every card states whether it concerns FH ULM or ULM generally."}</p></div><div><FileText size={18} /><p>{isIndonesian ? "Ringkasan ditulis ulang secara ringkas dan setia pada inti sumber, bukan disalin." : "Summaries are written afresh, briefly and faithfully, rather than copied."}</p></div><div><ShieldCheck size={18} /><p>{isIndonesian ? "Tautan keluar selalu tersedia agar pembaca dapat memeriksa konteks lengkapnya." : "An outbound link is always available so readers can check the full context."}</p></div></div></section>
    <section className="content-width perspectives-layout" aria-label={isIndonesian ? "Daftar perspektif publik" : "Public perspectives list"}><aside className="perspectives-rail"><div className="rail-stamp"><span>{isIndonesian ? "BERKAS BACA" : "READING FILE"}</span><strong>02</strong><small>{isIndonesian ? "suara publik" : "public voices"}</small></div><RiverThread label={isIndonesian ? "aliran sumber" : "source current"} /><div className="rail-count"><strong>03</strong><span>{isIndonesian ? "ULM secara umum" : "ULM generally"}</span></div><div className="rail-count"><strong>03</strong><span>{isIndonesian ? "Fakultas Hukum" : "Faculty of Law"}</span></div><p className="rail-footnote">{isIndonesian ? "Dipilih untuk keterbacaan sumber, bukan popularitas." : "Selected for source readability, not popularity."}</p></aside><div><RiverThread label={isIndonesian ? "catatan terpilih" : "selected notes"} /><div className="perspectives-list">{perspectives.map((item) => { const platform = platformInfo[item.platform]; return <article className="perspective-card" key={item.id} style={{ "--platform": platform.color } as React.CSSProperties}><div className="case-file-tab"><div className="platform-badge"><span className="platform-mark"><img src={platform.logo} alt={`${item.platform} logo`} /></span><span>{item.platform}</span></div><span className="entry-id">{item.id}</span></div><div className="perspective-tags"><span>{isIndonesian ? item.scopeId : item.scopeEn}</span><span>{isIndonesian ? item.relationshipId : item.relationshipEn}</span></div><h2>{isIndonesian ? item.titleId : item.titleEn}</h2><p className="perspective-body">{isIndonesian ? item.bodyId : item.bodyEn}</p><div className="perspective-card-bottom"><span>{isIndonesian ? item.dateId : item.dateEn}</span><a href={item.href} target="_blank" rel="noreferrer" className="platform-link">{isIndonesian ? platform.actionId : platform.actionEn}<ArrowUpRight size={16} /></a></div></article>; })}</div></div></section>
    <section id="source-boundary" className="content-width source-boundary"><MessageCircleMore size={23} /><div><p className="eyebrow">{isIndonesian ? "Batas editorial" : "Editorial boundary"}</p><h2>{isIndonesian ? "Yang tidak masuk juga penting." : "What is not included matters too."}</h2><p>{isIndonesian ? "Penelusuran ini tidak menemukan cukup unggahan Reddit, ulasan Google Maps individual, forum, atau komentar media sosial yang dapat diakses dan diverifikasi secara aman untuk dimasukkan. Alih-alih mengisi halaman dengan konten lemah, halaman ini berhenti pada enam sumber yang memenuhi standar." : "This research did not find enough Reddit posts, individual Google Maps reviews, forum posts, or social-media comments that could be accessed and safely verified for inclusion. Rather than fill the page with weak material, it stops at the six sources meeting the standard."}</p></div></section>
  </>;
}
