/** River Margin / shULM: the prosecutor path is a dated public-process map, never a personal eligibility opinion or a recruitment promise. */
import { ArrowRight, BriefcaseBusiness, ClipboardCheck, GraduationCap, ShieldAlert, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { SourceLink } from "@/components/SourceLink";
import { useLanguage } from "@/contexts/LanguageContext";
import { externalLinks, prosecutorCareerSteps } from "@/lib/site-data";

export default function Career() { const { language, isIndonesian } = useLanguage(); const stepIcons = [GraduationCap, ClipboardCheck, BriefcaseBusiness, ShieldCheck]; return <><PageIntro label={isIndonesian ? "Jalur Karier" : "Career Path"} title={isIndonesian ? "Arah studi menuju profesi jaksa." : "An academic direction toward prosecution."} summary={isIndonesian ? "Ini adalah peta proses publik, bukan penilaian kelayakan pribadi, jaminan pekerjaan, atau pengganti pengumuman rekrutmen resmi." : "This is a map of public process, not a personal eligibility assessment, employment guarantee, or substitute for official recruitment announcements."} /><section className="content-width career-steps">{prosecutorCareerSteps.map((step, index) => { const IconComponent = stepIcons[index]; return <article className="career-step" key={step.step}><span className="step-count">{step.step}</span><div className="step-icon"><IconComponent size={22} /></div><h2>{step[language]}</h2><p>{isIndonesian ? step.descId : step.descEn}</p>{index < prosecutorCareerSteps.length - 1 && <ArrowRight className="step-arrow" size={20} />}</article>; })}</section><section className="content-width career-source-panel"><div><p className="eyebrow">{isIndonesian ? "Titik rujukan resmi" : "Official reference points"}</p><h2>{isIndonesian ? "Pantau seleksi; pahami prosesnya." : "Monitor selection; understand the process."}</h2><p>{isIndonesian ? "Kanal Seleksi CASN Kejaksaan RI menyatakan dirinya sebagai platform resmi kegiatan seleksi CPNS/CPPPK Kejaksaan. Berita Badiklat Kejaksaan RI menambah konteks bahwa PPPJ merupakan tahap pembentukan yang mendahului pelantikan Ajun Jaksa bagi peserta terpilih. Persyaratan, formasi, jadwal, dan kelayakan pribadi berubah menurut pengumuman; periksa langsung sebelum mengambil tindakan." : "The Kejaksaan RI CASN Selection Channel identifies itself as the official platform for Kejaksaan CPNS/CPPPK selection. Badiklat Kejaksaan RI news adds the context that PPPJ is a formation stage preceding appointment as Ajun Jaksa for selected participants. Requirements, vacancies, schedules, and individual eligibility change by notice; check directly before acting."}</p><div className="source-row"><SourceLink href={externalLinks.kejaksaan} label={isIndonesian ? "Kanal Seleksi CASN" : "CASN Selection Channel"} /><SourceLink href={externalLinks.pppj} label={isIndonesian ? "Berita PPPJ & Ajun Jaksa" : "PPPJ and Ajun Jaksa news"} /></div></div><div className="career-seal"><span>PPPJ</span><small>{isIndonesian ? "periksa ulang" : "recheck"}</small></div></section><section className="content-width warning-strip"><ShieldAlert size={20} /><p>{isIndonesian ? "Waspada informasi rekrutmen palsu dan syarat yang sudah kedaluwarsa. Telusuri pengumuman resmi pada periode berjalan." : "Beware of false recruitment information and outdated criteria. Trace the official announcement for the active period."}</p></section>
    <section className="content-width split-section mt-12 border-t border-zinc-200 dark:border-zinc-800 pt-12">
      <div className="section-heading">
        <p className="eyebrow">{isIndonesian ? "Kemitraan Strategis" : "Strategic Partnership"}</p>
        <h2>{isIndonesian ? "Kerja Sama Adhyaksa Chamber" : "Adhyaksa Chamber Collaboration"}</h2>
      </div>
      <div className="fact-list">
        <div><BriefcaseBusiness size={19} /><span><strong>{isIndonesian ? "Pusat Mediasi Sektor Publik" : "Public Sector Mediation Center"}</strong><small>{isIndonesian ? "Kejaksaan Agung RI memilih FH ULM sebagai kampus pertama dan satu-satunya di Indonesia untuk uji sahih Adhyaksa Chamber (Pusat mediasi sengketa perdata & TUN)." : "Kejaksaan Agung RI selected FH ULM as the first and only campus in Indonesia for the Adhyaksa Chamber blueprint (Civil & Administrative dispute mediation)."}</small></span></div>
        <div><BriefcaseBusiness size={19} /><span><strong>{isIndonesian ? "Keterkaitan Karir" : "Career Relevance"}</strong><small>{isIndonesian ? "Ini memperkuat posisi ULM dalam relasi Datun (Perdata & Tata Usaha Negara) Kejaksaan." : "This strengthens ULM's position in the Kejaksaan's civil and administrative sectors."}</small></span></div>
      </div>
    </section>

  </>; }
