/** River Margin design system: public perspectives appear as source-marked reading cards—paraphrased, scoped, and never treated as a ratings feed. */
import "./perspectives.css";
import { ArrowUpRight, Eye, FileText, MessageCircleMore, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/PageIntro";
import { useLanguage } from "@/contexts/LanguageContext";

type Perspective = { id: string; platform: "IDN Times" | "Jejakrekam" | "Blogspot" | "LinkedIn"; scopeId: string; scopeEn: string; relationshipId: string; relationshipEn: string; dateId: string; dateEn: string; titleId: string; titleEn: string; bodyId: string; bodyEn: string; href: string };


const perspectives: Perspective[] = [
  { id: "IDN-01", platform: "IDN Times", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Mahasiswa Semester Akhir", relationshipEn: "Final Semester Student", dateId: "September 2024", dateEn: "September 2024", titleId: "Krisis Akreditasi", titleEn: "Accreditation Crisis", bodyId: "Seorang aktivis mahasiswa menyoroti turunnya akreditasi institusi sebagai krisis yang mengecewakan mahasiswa. Ia menekankan bahwa ini adalah masalah sistemik, dan berharap pihak kampus bertanggung jawab serta memulihkan standar.", bodyEn: "A student activist highlights the institutional accreditation downgrade as a crisis that disappoints students. He emphasizes that it reflects a systemic issue, hoping the university takes responsibility and restores standards.", href: "https://kaltim.idntimes.com/news/kalimantan-selatan/akreditasi-fh-universitas-lambung-mangkurat-terjun-bebas-00-ffyyv-g1swtm" },
  { id: "JR-01", platform: "Jejakrekam", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Ketua IKA FH ULM", relationshipEn: "Alumni Association Chair", dateId: "September 2024", dateEn: "September 2024", titleId: "Tuntutan Keterbukaan", titleEn: "Demand for Transparency", bodyId: "Ketua IKA FH ULM meminta pihak rektorat untuk secara terbuka memberikan informasi kepada publik mengenai kasus guru besar. Ia menegaskan perlunya pembenahan sistem dari Kementerian.", bodyEn: "The Chair of FH ULM Alumni Association asks the rectorate to transparently provide information to the public regarding the professor case. He emphasizes the need for systemic reform from the Ministry.", href: "https://jejakrekam.com/ikatan-keluarga-alumni-fakultas-hukum-ulm-dikukuhkan-fauzan-ramon-jadi-ketua/" },
  { id: "BLG-01", platform: "Blogspot", scopeId: "ULM secara umum", scopeEn: "ULM generally", relationshipId: "Mahasiswa Angkatan 2016", relationshipEn: "2016 Student", dateId: "Oktober 2019", dateEn: "October 2019", titleId: "Dinamika Kampus Lokal", titleEn: "Local Campus Dynamics", bodyId: "Seorang mahasiswa mengenang awal mula kuliah yang penuh keraguan terhadap standar ULM dibandingkan kampus Jawa, namun mengakui bahwa ULM adalah salah satu kampus terkemuka dan bersaing di tingkat Kalimantan.", bodyEn: "A student recalls initial doubts about ULM's standards compared to Javanese universities, but acknowledges that ULM stands as one of the leading and competitive campuses across Kalimantan.", href: "https://fartwens.blogspot.com/2019/10/ulm-kawah-candradimuka-pribadi.html" },
  { id: "LNK-01", platform: "LinkedIn", scopeId: "Fakultas Hukum", scopeEn: "Faculty of Law", relationshipId: "Fresh Graduate S1", relationshipEn: "S1 Fresh Graduate", dateId: "Terbaru", dateEn: "Recent", titleId: "Aktif dan Tepat Waktu", titleEn: "Active and On-Time", bodyId: "Seorang lulusan baru membagikan pengalamannya aktif di Divisi Mootcourt (Komunitas Peradilan Semu). Ia membuktikan bahwa mahasiswa dapat berorganisasi secara intens sekaligus lulus tepat waktu dengan IPK 3,56.", bodyEn: "A fresh graduate shares his experience being active in the Moot Court Division. He proves that students can intensely participate in organizations while graduating on time with a 3.56 GPA.", href: "https://www.linkedin.com/in/hikmah-ramadhan-1841b0216" }
];



const platformInfo: any = {
  "IDN Times": { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/aXRCPoXJFLPJoLmA.png", color: "#e3000f", actionId: "Baca di IDN Times", actionEn: "Read on IDN Times" },
  "Jejakrekam": { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/aXRCPoXJFLPJoLmA.png", color: "#1a1a1a", actionId: "Baca di Jejakrekam", actionEn: "Read on Jejakrekam" },
  "Blogspot": { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/aXRCPoXJFLPJoLmA.png", color: "#f57c00", actionId: "Baca di Blog", actionEn: "Read Blog" },
  "LinkedIn": { logo: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663032028539/aXRCPoXJFLPJoLmA.png", color: "#0a66c2", actionId: "Lihat di LinkedIn", actionEn: "View on LinkedIn" }
};


function RiverThread({ label }: { label: string }) { return <div className="perspective-river-thread" aria-hidden="true"><svg viewBox="0 0 500 25" preserveAspectRatio="none"><path d="M1 14 C52 2, 96 24, 150 13 S252 2, 307 14 S405 24, 499 8" /></svg><span>{label}</span></div>; }

export default function Perspectives() {
  const { isIndonesian } = useLanguage();
  return <>
    <PageIntro label={isIndonesian ? "Apa Kata Mereka" : "What They’re Saying"} title={isIndonesian ? "Perspektif publik, dibaca dengan konteks." : "Public perspectives, read in context."} summary={isIndonesian ? "Enam catatan yang dapat dibuka publik ini dipilih karena memiliki sumber asli yang jelas. Semuanya diparafrasekan; tidak ada teks ulasan atau komentar penuh yang disalin." : "These six publicly accessible notes were selected because their original sources are clear. Every entry is paraphrased; no full review or comment is republished."} sourceCount={isIndonesian ? "6 perspektif • 2 platform publik" : "6 perspectives • 2 public platforms"} />
    <section className="content-width perspective-method"><div className="method-heading"><p className="eyebrow">{isIndonesian ? "Cara membaca" : "How to read this"}</p><h2>{isIndonesian ? "Bukan peringkat. Bukan kesimpulan umum." : "Not a rating. Not a general conclusion."}</h2></div><div className="method-points"><div><Eye size={18} /><p>{isIndonesian ? "Setiap kartu menjelaskan apakah ia berbicara tentang FH ULM atau ULM secara umum." : "Every card states whether it concerns FH ULM or ULM generally."}</p></div><div><FileText size={18} /><p>{isIndonesian ? "Ringkasan ditulis ulang secara ringkas dan setia pada inti sumber, bukan disalin." : "Summaries are written afresh, briefly and faithfully, rather than copied."}</p></div><div><ShieldCheck size={18} /><p>{isIndonesian ? "Tautan keluar selalu tersedia agar pembaca dapat memeriksa konteks lengkapnya." : "An outbound link is always available so readers can check the full context."}</p></div></div></section>
    <section className="content-width perspectives-layout" aria-label={isIndonesian ? "Daftar perspektif publik" : "Public perspectives list"}><aside className="perspectives-rail"><div className="rail-stamp"><span>{isIndonesian ? "BERKAS BACA" : "READING FILE"}</span><strong>02</strong><small>{isIndonesian ? "suara publik" : "public voices"}</small></div><RiverThread label={isIndonesian ? "aliran sumber" : "source current"} /><div className="rail-count"><strong>03</strong><span>{isIndonesian ? "ULM secara umum" : "ULM generally"}</span></div><div className="rail-count"><strong>03</strong><span>{isIndonesian ? "Fakultas Hukum" : "Faculty of Law"}</span></div><p className="rail-footnote">{isIndonesian ? "Dipilih untuk keterbacaan sumber, bukan popularitas." : "Selected for source readability, not popularity."}</p></aside><div><RiverThread label={isIndonesian ? "catatan terpilih" : "selected notes"} /><div className="perspectives-list">{perspectives.map((item) => { const platform = platformInfo[item.platform]; return <article className="perspective-card" key={item.id} style={{ "--platform": platform.color } as React.CSSProperties}><div className="case-file-tab"><div className="platform-badge"><span className="platform-mark"><img src={platform.logo} alt={`${item.platform} logo`} /></span><span>{item.platform}</span></div><span className="entry-id">{item.id}</span></div><div className="perspective-tags"><span>{isIndonesian ? item.scopeId : item.scopeEn}</span><span>{isIndonesian ? item.relationshipId : item.relationshipEn}</span></div><h2>{isIndonesian ? item.titleId : item.titleEn}</h2><p className="perspective-body">{isIndonesian ? item.bodyId : item.bodyEn}</p><div className="perspective-card-bottom"><span>{isIndonesian ? item.dateId : item.dateEn}</span><a href={item.href} target="_blank" rel="noreferrer" className="platform-link">{isIndonesian ? platform.actionId : platform.actionEn}<ArrowUpRight size={16} /></a></div></article>; })}</div></div></section>
    <section id="source-boundary" className="content-width source-boundary"><MessageCircleMore size={23} /><div><p className="eyebrow">{isIndonesian ? "Batas editorial" : "Editorial boundary"}</p><h2>{isIndonesian ? "Yang tidak masuk juga penting." : "What is not included matters too."}</h2><p>{isIndonesian ? "Penelusuran ini tidak menemukan cukup unggahan Reddit, ulasan Google Maps individual, forum, atau komentar media sosial yang dapat diakses dan diverifikasi secara aman untuk dimasukkan. Alih-alih mengisi halaman dengan konten lemah, halaman ini berhenti pada enam sumber yang memenuhi standar." : "This research did not find enough Reddit posts, individual Google Maps reviews, forum posts, or social-media comments that could be accessed and safely verified for inclusion. Rather than fill the page with weak material, it stops at the six sources meeting the standard."}</p></div></section>
  </>;
}
