/** River Margin design system: persistent shULM navigation behaves like a marked legal notebook, with a source-aware footer. */
import { ArrowUpRight, Languages, Menu, X } from "lucide-react";
import { type PropsWithChildren, useState } from "react";
import { Link, useLocation } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";
import { externalLinks, imagery, translations } from "@/lib/site-data";
function Wordmark() { return <Link href="/" className="wordmark" aria-label="Saku Hukum ULM — kembali ke beranda"><span>sh</span><strong>ULM</strong></Link>; }
export function SiteFrame({ children }: PropsWithChildren) {
  const [location] = useLocation(); const { language, toggleLanguage, isIndonesian } = useLanguage(); const [menuOpen, setMenuOpen] = useState(false); const copy = translations[language]; const navItems = copy.nav as readonly (readonly [string, string])[];
  return <div className="site-frame"><header className="site-header"><div className="header-inner"><Wordmark /><nav className="desktop-nav" aria-label={isIndonesian ? "Navigasi utama" : "Main navigation"}>{navItems.map(([label, href]) => <Link key={href} href={href} className={location === href ? "nav-link is-active" : "nav-link"}>{label}</Link>)}</nav><div className="header-actions"><button className="language-toggle" type="button" onClick={toggleLanguage} aria-label={copy.switchLanguage}><Languages size={15} strokeWidth={1.8} /><span>{language === "id" ? "EN" : "ID"}</span></button><button className="menu-toggle" type="button" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? copy.closeMenu : copy.openMenu} aria-expanded={menuOpen}>{menuOpen ? <X size={21} /> : <Menu size={22} />}</button></div></div>{menuOpen && <div className="mobile-nav-wrap"><nav className="mobile-nav" aria-label={isIndonesian ? "Navigasi utama" : "Main navigation"}>{navItems.map(([label, href], index) => <Link key={href} href={href} onClick={() => setMenuOpen(false)} className={location === href ? "mobile-nav-link is-active" : "mobile-nav-link"}><span className="nav-index">0{index + 1}</span>{label}</Link>)}</nav></div>}</header><main>{children}</main><footer className="site-footer"><div className="footer-top"><div className="footer-brand"><img src={imagery.mark} alt="" className="footer-symbol" /><div><p className="footer-title">Saku Hukum ULM</p><p>{copy.footerNote}</p></div></div><div className="footer-links"><a href={externalLinks.faculty} target="_blank" rel="noreferrer">FH ULM <ArrowUpRight size={14} /></a><a href={externalLinks.curriculumPdf} target="_blank" rel="noreferrer">Kurikulum 2020 <ArrowUpRight size={14} /></a><a href={externalLinks.repository} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14} /></a></div></div><div className="footer-bottom"><p>{copy.personalNotice}</p><p>© {new Date().getFullYear()} Saku Hukum ULM</p></div></footer></div>;
}
